jdbc.driver_class=com.mysql.cj.jdbc.Driver
# Note: because of a reported bug in mysql driver, adding the following to the URL (otherwise exception may occur): useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
//jdbc.url=jdbc:mysql://localhost/cs548_reststudentdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
//jdbc.username=reststudentuser
//jdbc.password=zupassword

dbc.url=jdbc:mysql://127.0.0.1:3306/login_schema
jdbc.username=root
jdbc.password=Luoyh790504

# JPA/Hibernate related settings
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
hibernate.format_sql=true


